### ISSUE TITLE
5.2 UI Mockup for messages page (high fidelity, includes learning curve for drawing tool)

### ISSUE THREAD

**Issue by mpjacq** [helpsavecraigslist/project#14]

**Comment by peter-shell** [comment]
<img width="1712" alt="Screen Shot 2022-10-17 at 1 33 01 PM" src="https://user-images.githubusercontent.com/71984315/197656503-9a395990-1d83-40d1-92c6-f7d1e88d18d0.png">
<img width="1712" alt="Screen Shot 2022-10-17 at 1 32 52 PM" src="https://user-images.githubusercontent.com/71984315/197656511-9dd4522e-5651-44f7-88f9-f48e711caa97.png">
<img width="1136" alt="tablet" src="https://user-images.githubusercontent.com/71984315/197656517-b6ff3230-335b-430b-aeed-d71e44cfe83c.png">
<img width="532" alt="phone_reply_cont" src="https://user-images.githubusercontent.com/71984315/197656519-7d58eed2-92e1-4e24-ba06-e649cf383524.png">
<img width="532" alt="phone_reply" src="https://user-images.githubusercontent.com/71984315/197656521-e8c3bfdd-7782-47bd-bf58-1ccbf528a188.png">
<img width="532" alt="phone_messages" src="https://user-images.githubusercontent.com/71984315/197656522-fd6b9e42-b7d3-41d5-99a5-e008402987ee.png">
<img width="1712" alt="full_size_PC" src="https://user-images.githubusercontent.com/71984315/197656525-27021d80-c442-4476-bf40-9979e4f3a90c.png">
