### ISSUE TITLE
5.9 Connect Ads with Message functionality 

### ISSUE THREAD

**Issue by mpjacq** [helpsavecraigslist/project#38]
Currently doesn't do anything. Once messaging functionality is implemented, integrate. Take user to page to compose new message with recipient automatically filled in from items db data (PostedBy).

Assigning to everyone for now since this task crosses over both sections of the app. Can be updated later when it is determined who can take this one.

**Comment by peter-shell** [comment]
Half way complete. Button on items card sends user to new message screen but DB functionality is not currently implemented.

**Comment by mpjacq** [comment]
Updated issue title to match project plan, I added this one ad-hoc as I was thinking of it but it's covered in sprint 3 tasks.
