### ISSUE TITLE
"message seller" feature sends google auth id instead of username to new message screen

### ISSUE THREAD

**Issue by peter-shell** [helpsavecraigslist/project#75]
<img width="1166" alt="Screen Shot 2022-10-26 at 4 00 33 PM" src="https://user-images.githubusercontent.com/71984315/198156153-ce4c0e39-8e0c-4043-9eae-d758e0c64d46.png">

**Comment by jlipe** [comment]
Maybe this should show the persons email? The usernames are autogenerated and don't have a way to be updated currently

**Comment by peter-shell** [comment]
I like that idea. Craigslist show's a randomized email, a cutout, so the user doesn't see the actual seller's email. Maybe something like that? 
How do we keep track of users? Is the Google_#######.. value constant?
